"""added column nationality to author

Revision ID: 25ff86b2de25
Revises: 062b5daecae9
Create Date: 2022-06-26 15:14:56.708671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ff86b2de25'
down_revision = '062b5daecae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('nationality', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'nationality')
    # ### end Alembic commands ###
